version: '3.8'

services:
  database:
    image: mysql:5.7
    container_name: crudmysql_database_container
    ports:
      - "3307:3306"
    volumes:
      - ./database/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: 123456789
    networks:
      - crud_net

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: crudmysql_web_container
    ports:
      - "3000:3000"
    depends_on:
      - database
    command: sh -c './wait-for-it.sh -t 0 database:3306 -- npm start'
    networks:
      - crud_net

networks:
  crud_net:
    driver: bridge
